CREATE DATABASE IF NOT EXISTS FormDB;
USE FormDB;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone_number VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  gender VARCHAR(20)
);

-- Select statements to view the data
SELECT * FROM USERS;